import type { Dictionary } from './types';

export const en: Dictionary = {
  meta: {
    title: 'Petro Hordiienko · Software Engineer & Fractional CTO',
    description:
      'Independent software engineer and fractional CTO in Poznań. Web and mobile apps, backend, cloud, AI and blockchain, delivered personally by a senior engineer.',
    keywords: [
      'software engineer Poznań',
      'fractional CTO',
      'freelance software developer Poland',
      'web application development',
      'mobile app development',
      'backend and API development',
      'cloud and DevOps',
      'AI integration',
      'blockchain development',
      'fintech engineering',
    ],
  },
  nav: {
    services: 'Services',
    work: 'Portfolio',
    process: 'Process',
    contact: 'Contact',
    language: 'Language',
    menu: 'Menu',
    close: 'Close menu',
  },
  theme: { label: 'Theme', light: 'Light', dark: 'Dark' },
  hero: {
    notes: ['Independent software engineer', 'Est. 2016', '52.41° N · 16.93° E — Poznań'],
    titleTop: 'Ideas,',
    titleBottom: 'engineered.',
    lede: 'Software, systems and AI for teams that move fast. Senior engineering, delivered personally, without the agency overhead.',
    ctaBook: 'Start a project',
    ctaServices: 'What I build',
    canvasLabel: 'Animated gradient background',
    fieldLabel: 'Interactive flow field',
    fieldHint: 'Move to bend the flow · click to send a ripple',
    stackLabel: 'Stack',
    stack: [
      'Go',
      'TypeScript',
      'React',
      'Next.js',
      'Python',
      'Kubernetes',
      'Terraform',
      'PostgreSQL',
      'Solidity',
      'LLM · RAG',
      'WebRTC',
      'AWS · GCP',
    ],
  },
  manifesto: {
    label: 'About',
    text: 'I turn ideas into reliable, user-centric products for startups and growing teams.',
    textMuted:
      'Bridging technology and business strategy, so every solution works technically and delivers measurable value.',
    pillars: [
      {
        title: 'Results-driven engineering',
        body: 'Years of designing, building and delivering across industries, leading cross-functional teams and turning complex technical challenges into high-impact outcomes.',
      },
      {
        title: 'Startups, from idea to product',
        body: 'I help startups succeed by transforming ideas into reliable, user-centric products, with every decision tied to business value.',
      },
      {
        title: 'Crypto meets fiat',
        body: 'I work at the intersection of decentralized and traditional finance, combining crypto and fiat systems to change how people experience and interact with money.',
      },
      {
        title: 'AI that works today',
        body: 'Narrow AI already improves existing solutions and optimises processes. I build it into products now and design them for the more capable systems to come.',
      },
    ],
    facts: [
      { k: 'Building since', v: '2016' },
      { k: 'Former CTO', v: 'Crypto exchange' },
      { k: 'Principal engineer', v: 'AI data platform' },
      { k: 'Works', v: 'Remote · CET' },
    ],
  },
  services: {
    label: 'Services',
    title: 'Full-cycle',
    titleMuted: 'IT services',
    sub: 'From a first prototype to systems that handle real money and real traffic.',
    outcomeLabel: 'Outcome',
    pointsLabel: 'What you get',
    stackLabel: 'Stack',
    relatedLabel: 'Related work',
    detailsLabel: 'View details',
    closeLabel: 'Close',
    items: [
      {
        title: 'Web applications',
        related: ['crm', 'exchange', 'webgl'],
        body: 'SaaS products, dashboards and platforms that are fast, accessible and easy to grow.',
        points: [
          'SaaS products, admin tools and customer portals',
          'Server-rendered React and Next.js with strong performance',
          'Typed component libraries and design systems',
          'Real-time features over WebSocket',
        ],
        tech: ['React', 'Next.js', 'TypeScript', 'Node.js', 'Vue'],
        outcome: 'A fast product your team can keep extending.',
      },
      {
        title: 'Mobile apps',
        related: ['delivery', 'chat', 'mvp'],
        body: 'Cross-platform iOS and Android apps that share one codebase with your web product.',
        points: [
          'iOS and Android from a single codebase',
          'Native modules in Swift or Kotlin when the platform demands it',
          'Push notifications, OAuth sign-in and offline support',
          'Shared logic and APIs with your web product',
        ],
        tech: ['React Native', 'Flutter', 'Swift', 'Kotlin'],
        outcome: 'One team shipping to both app stores.',
      },
      {
        title: 'Backend & APIs',
        related: ['audio', 'exchange', 'chat'],
        body: 'Services, integrations and real-time systems designed for load and for change.',
        points: [
          'REST, GraphQL and gRPC APIs',
          'Microservices and event-driven architecture',
          'Real-time audio and video: WebRTC, VoIP and SIP',
          'Designed for high load and high availability',
        ],
        tech: ['Go', 'Node.js', 'Python', 'gRPC', 'PostgreSQL', 'Redis'],
        outcome: 'Services that stay fast and stable as traffic grows.',
      },
      {
        title: 'Cloud & DevOps',
        related: ['cloud', 'exchange', 'audio'],
        body: 'Infrastructure as code, CI/CD, monitoring and high availability on any cloud.',
        points: [
          'Infrastructure as code with Terraform',
          'Kubernetes, GitOps and CI/CD pipelines',
          'Observability with Prometheus, Grafana, ELK and Jaeger',
          'Cloud or bare metal: AWS, GCP and Azure',
        ],
        tech: ['Kubernetes', 'Terraform', 'ArgoCD', 'Docker', 'AWS', 'GCP'],
        outcome: 'Repeatable releases and an environment you can trust.',
      },
      {
        title: 'AI integration',
        related: ['data'],
        body: 'LLM features, agents and RAG that solve a measurable problem inside your product.',
        points: [
          'LLM features and modular agent orchestration',
          'RAG and prompt engineering with evaluation',
          'Model Context Protocol integrations',
          'Human-in-the-loop workflows where accuracy matters',
        ],
        tech: ['LLM', 'RAG', 'MCP', 'Agents', 'Python', 'FastAPI'],
        outcome: 'AI that improves a real process, not a demo.',
      },
      {
        title: 'Blockchain & fintech',
        related: ['exchange'],
        body: 'Exchanges, trading engines, wallets and payment flows with security built in.',
        points: [
          'Exchange and trading-engine architecture',
          'Wallets and payment flows across crypto and fiat',
          'Smart contracts and EVM integrations',
          'Security and compliance designed in from day one',
        ],
        tech: ['Solidity', 'EVM', 'Web3', 'Go', 'Kubernetes'],
        outcome: 'Financial systems that are secure and keep running.',
      },
      {
        title: 'Data engineering',
        related: ['data'],
        body: 'Pipelines, data quality and analytics foundations you can trust for decisions.',
        points: [
          'ETL pipelines and dataset profiling',
          'Data-quality scoring and anomaly detection',
          'Analytics and reporting foundations',
          'Scalable, multi-workspace platforms',
        ],
        tech: ['Python', 'PostgreSQL', 'ELK', 'ETL', 'Go'],
        outcome: 'Data your team can rely on for decisions.',
      },
      {
        title: 'Consulting & audits',
        related: ['mvp', 'cloud'],
        body: 'Architecture reviews, code and vendor audits, technical due diligence.',
        points: [
          'Architecture reviews and technical due diligence',
          'Code, security and vendor audits',
          'Roadmap, hiring and investor conversations as fractional CTO',
          'Scaling plans for growing teams',
        ],
        tech: ['Architecture', 'Security', 'Scale'],
        outcome: 'Clear decisions and a plan you can act on.',
      },
    ],
    cto: {
      strong: 'Fractional CTO.',
      body: ' Senior technical leadership a few days a month: roadmap, hiring, architecture and investor conversations.',
      cta: 'Discuss your project',
    },
  },
  work: {
    label: 'Work',
    title: 'Selected',
    titleMuted: 'portfolio',
    sub: 'Products across web, mobile and backend, with the workflows behind them. Open any project to step through its screens.',
    filterLabel: 'Filter by',
    dialog: {
      close: 'Close',
      workflow: 'Workflow',
      prev: 'Previous step',
      next: 'Next step',
      open: 'View workflow',
    },
    filters: {
      all: 'All',
      web: 'Web',
      mobile: 'Mobile',
      backend: 'Backend',
      ai: 'AI',
      fintech: 'Fintech',
      realtime: 'Real-time',
      webgl: 'WebGL',
      wasm: 'WebAssembly',
    },
    items: [
      {
        kind: 'exchange',
        workflow: [
          { title: 'Trade', caption: 'Live chart, order book and one-click order entry.' },
          { title: 'Hold', caption: 'Balances and wallets across crypto and fiat.' },
          { title: 'Confirm', caption: 'Order review, risk checks and instant confirmation.' },
        ],
        categories: ['fintech', 'web', 'backend'],
        title: 'Crypto exchange platform',
        summary:
          'Trading engine, wallets and a web trading terminal for a Dubai-based exchange, led from architecture to production.',
        highlights: [
          'Microservices on Kubernetes with high availability',
          'HD wallets and EVM blockchain integrations',
          'Security and compliance built into the core',
        ],
        platforms: ['Web', 'API'],
        stack: ['Go', 'Next.js', 'Solidity', 'PostgreSQL', 'Kubernetes', 'Redis'],
        role: 'CTO',
        company: 'Exbi Trade · Bistox',
        when: '2021–23',
      },
      {
        kind: 'data',
        workflow: [
          { title: 'Profile', caption: 'Upload a dataset and see its structure and gaps.' },
          {
            title: 'Score',
            caption: 'Quality scored across completeness, accuracy and integrity.',
          },
          { title: 'Review', caption: 'An agent proposes fixes; a human approves them.' },
        ],
        categories: ['ai', 'web', 'backend'],
        title: 'AI data-quality platform',
        summary:
          'A platform that turns raw, unstructured data into trusted information through profiling, anomaly detection and imputation.',
        highlights: [
          'Dataset profiling with quality scoring',
          'LLM agents with human-in-the-loop decisions',
          'Multi-workspace, scalable architecture',
        ],
        platforms: ['Web', 'API'],
        stack: ['Python', 'Go', 'React', 'FastAPI', 'LLM', 'MCP'],
        role: 'Principal Engineer',
        company: 'Octocleanse',
        when: '2024–25',
      },
      {
        kind: 'audio',
        workflow: [
          { title: 'Play', caption: 'Multi-source audio mixed into one live stream.' },
          { title: 'Mix', caption: 'Per-channel levels adjusted in real time.' },
          { title: 'Monitor', caption: 'Latency and listener metrics at a glance.' },
        ],
        categories: ['realtime', 'backend'],
        title: 'Real-time audio streaming',
        summary:
          'An audiobook streaming service that mixes several sources into a single live output with low latency.',
        highlights: [
          'WebRTC and gRPC transport',
          'Container orchestration on DigitalOcean',
          'Infrastructure as code with Terraform',
        ],
        platforms: ['Web', 'API'],
        stack: ['Go', 'WebRTC', 'gRPC', 'Terraform', 'PostgreSQL'],
        role: 'Senior Engineer',
        company: 'Wowsy',
        when: '2024–25',
      },
      {
        kind: 'chat',
        workflow: [
          { title: 'Chat', caption: 'Channels, threads and rich messages.' },
          { title: 'Call', caption: 'Conference calls inside the conversation.' },
          { title: 'Automate', caption: 'Workflows triggered by messages and integrations.' },
        ],
        categories: ['realtime', 'web', 'mobile'],
        title: 'Team chat with calling',
        summary:
          'An AI-powered team messenger with conference calls over PBX, push notifications and workflow automation.',
        highlights: [
          'Conference calls with SIP and Freeswitch',
          'OAuth 2.0 and third-party integrations',
          'Zapier and IFTTT automation workflows',
        ],
        platforms: ['Web', 'iOS', 'Android'],
        stack: ['Node.js', 'Angular', 'Ionic', 'WebRTC', 'MongoDB'],
        role: 'Software Engineer',
        company: 'Chanty',
        when: '2018–19',
      },
      {
        kind: 'delivery',
        workflow: [
          { title: 'Find', caption: 'Search trips and compare offers on the way.' },
          { title: 'Track', caption: 'Follow the parcel live on the map.' },
          { title: 'Hand over', caption: 'Confirm delivery with a secure code.' },
        ],
        categories: ['mobile', 'web'],
        title: 'Peer-to-peer delivery marketplace',
        summary:
          'Web and native mobile apps connecting senders with travellers, built for rapid iteration on a startup budget.',
        highlights: [
          'React Native plus native Kotlin and Swift modules',
          'GraphQL, gRPC and RabbitMQ services',
          'Kubernetes with a full automated test suite',
        ],
        platforms: ['Web', 'iOS', 'Android'],
        stack: ['React Native', 'TypeScript', 'GraphQL', 'Kotlin', 'Swift', 'Kubernetes'],
        role: 'Full Stack Engineer',
        company: 'Voypost',
        when: '2017–21',
      },
      {
        kind: 'crm',
        workflow: [
          { title: 'Overview', caption: 'Revenue, pipeline and activity in one dashboard.' },
          { title: 'Pipeline', caption: 'Deals moved across stages with drag and drop.' },
          { title: 'Customer', caption: 'Full history and follow-ups per contact.' },
        ],
        categories: ['web', 'mobile'],
        title: 'CRM and ERP suite',
        summary:
          'Business-management systems and hybrid mobile apps for mid-sized companies, delivered as scalable SaaS.',
        highlights: [
          'Modular dashboards, roles and reports',
          'Hybrid mobile companion apps',
          'Deployed and operated on AWS and Google Cloud',
        ],
        platforms: ['Web', 'iOS', 'Android'],
        stack: ['Angular', 'Node.js', 'Ionic', 'PostgreSQL', 'AWS'],
        role: 'Full Stack Engineer',
        company: 'MaybeWorks',
        when: '2016–18',
      },
      {
        kind: 'mvp',
        workflow: [
          { title: 'Onboard', caption: 'A friendly first-run flow on mobile.' },
          { title: 'Launch', caption: 'A landing page that explains the value fast.' },
          { title: 'Operate', caption: 'An admin dashboard for the first customers.' },
        ],
        categories: ['mobile', 'web'],
        title: 'MVP development for startups',
        summary:
          'End-to-end MVPs for international clients, from market research and product design to launch.',
        highlights: [
          'Web, iOS and Android from one team',
          'Agile delivery with clear milestones',
          'Hand-over with documentation and CI/CD',
        ],
        platforms: ['Web', 'iOS', 'Android'],
        stack: ['Next.js', 'Flutter', 'React Native', 'FastAPI', 'Firebase'],
        role: 'CTO & Co-founder',
        company: 'DevStation',
        when: '2020–21',
      },
      {
        kind: 'cloud',
        workflow: [
          { title: 'Observe', caption: 'Metrics and alerts across every service.' },
          { title: 'Deliver', caption: 'A GitOps pipeline from commit to production.' },
          { title: 'Scale', caption: 'Pods and nodes scheduled automatically.' },
        ],
        categories: ['backend'],
        title: 'Cloud-native infrastructure',
        summary:
          'Production Kubernetes platforms with GitOps delivery, observability and high availability on cloud or bare metal.',
        highlights: [
          'Terraform and ArgoCD pipelines',
          'Prometheus, Grafana, ELK and Jaeger observability',
          'Mission-critical uptime for trading systems',
        ],
        platforms: ['API'],
        stack: ['Kubernetes', 'Terraform', 'ArgoCD', 'Grafana', 'AWS', 'GCP'],
        role: 'CTO & Engineer',
        company: 'Multiple clients',
        when: '2020–24',
      },
      {
        kind: 'webgl',
        workflow: [
          { title: 'Configure', caption: 'A real-time 3D scene customised with live controls.' },
          { title: 'Explore', caption: 'Large datasets rendered as an interactive point cloud.' },
          { title: 'Inspect', caption: 'A scene graph and tools for fine-tuning.' },
        ],
        categories: ['webgl', 'web'],
        title: 'Interactive 3D web experiences',
        summary:
          'Real-time WebGL product configurators, data visualisations and immersive landing pages that run smoothly on any device.',
        highlights: [
          'Custom shaders and GPU particle systems',
          'Interactive 3D product configurators',
          'Tuned for 60 fps on mobile and desktop',
        ],
        platforms: ['Web'],
        stack: ['WebGL', 'GLSL', 'Three.js', 'TypeScript', 'React'],
        role: 'Creative Engineer',
        company: 'Selected projects',
        when: '2022–26',
      },
      {
        kind: 'wasm',
        workflow: [
          { title: 'Process', caption: 'Heavy image filters running at near-native speed.' },
          { title: 'Benchmark', caption: 'The same task in JavaScript and WebAssembly.' },
          { title: 'Compose', caption: 'Timeline editing and export, fully in the browser.' },
        ],
        categories: ['wasm', 'web'],
        title: 'In-browser processing with WebAssembly',
        summary:
          'Compute-heavy image, media and data processing compiled to WebAssembly so it runs privately in the browser at near-native speed.',
        highlights: [
          'Rust and C++ compiled to WebAssembly',
          'Multi-threaded workers and shared memory',
          'Files never leave the user device',
        ],
        platforms: ['Web'],
        stack: ['WebAssembly', 'Rust', 'C++', 'Web Workers', 'TypeScript'],
        role: 'Software Engineer',
        company: 'Selected projects',
        when: '2022–26',
      },
    ],
  },
  process: {
    label: 'Process',
    title: 'Clear steps,',
    titleMuted: 'working software every week',
    steps: [
      {
        title: 'Intro call',
        body: '30 minutes about your goal, users and constraints. No preparation needed.',
        time: '30 MIN',
      },
      {
        title: 'Scope & estimate',
        body: 'A short written plan: architecture, milestones, risks and a cost range.',
        time: '2–3 DAYS',
      },
      {
        title: 'Build in increments',
        body: 'Weekly demos on a staging environment. Progress you can click, not status reports.',
        time: 'WEEKLY DEMOS',
      },
      {
        title: 'Launch & handover',
        body: 'Production release, documentation and support, or a handover to your team.',
        time: '1 WEEK',
      },
    ],
    modelLabel: 'Engagement',
    models: [
      {
        title: 'Fixed-scope MVP',
        body: 'Agreed scope and price for a first version.',
      },
      {
        title: 'Monthly B2B contract',
        body: 'Ongoing engineering, invoiced monthly.',
      },
      {
        title: 'Advisory days',
        body: 'Fractional CTO time, audits and reviews.',
      },
    ],
  },
  contact: {
    label: 'Contact',
    title: "Have an idea? Let's build it.",
    sub: 'Tell me what you are working on and where you are stuck.',
    copy: 'Copy',
    copied: 'Copied',
    note: 'Every enquiry is read by Petro personally.',
  },
  footer: {
    ceidg: 'Registered in CEIDG',
  },
};
